### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by xinggonglie** [Skythinker616/gpt-assistant-android#16]
![Screenshot_2023-12-11-10-03-18-099_com.miui.thirdappassistant.jpg](https://github.com/Skythinker616/gpt-assistant-android/assets/109005556/f0ad045d-d7f1-4abf-a3bf-1174f2aeba98)

cn.hutool.json.JSONException: Unterminated string at 10 [character 0 line 3]
	at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:413)
	at cn.hutool.json.JSONTokener.nextString(JSONTokener.java:242)
	at cn.hutool.json.JSONTokener.nextValue(JSONTokener.java:338)
	at cn.hutool.json.JSONParser.parseTo(JSONParser.java:69)
	at cn.hutool.json.ObjectMapper.mapFromTokener(ObjectMapper.java:240)
	at cn.hutool.json.ObjectMapper.mapFromStr(ObjectMapper.java:216)
	at cn.hutool.json.ObjectMapper.map(ObjectMapper.java:98)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:210)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:187)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:142)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:125)
	at com.skythinker.gptassistant.MainActivity$3.lambda$onFinished$1$com-skythinker-gptassistant-MainActivity$3(MainActivity.java:289)
	at com.skythinker.gptassistant.MainActivity$3$$ExternalSyntheticLambda3.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8152)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by Skythinker616** [comment]
该错误似乎由于GPT返回格式不标准导致，请问该错误是否能够稳定复现？希望能提供报错时所使用的GPT模型和prompt。

**Comment by xinggonglie** [comment]
我没在用，手机跳出的提示



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月11日(周一) 中午11:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Skythinker616/gpt-assistant-android] 闪退 (Issue #16)




 
该错误似乎由于GPT返回格式不标准导致，请问该错误是否能够稳定复现？希望能提供报错时所使用的GPT模型和prompt。

**Comment by Skythinker616** [comment]
可能是误触了音量键？如果无法复现的话我会关闭本issue，后续版本将会捕获该错误以避免崩溃。

**Comment by xinggonglie** [comment]
跟音量键应该没关系，无障碍模式我给关了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月11日(周一) 中午11:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Skythinker616/gpt-assistant-android] 闪退 (Issue #16)




 
可能是误触了音量键？如果无法复现的话我会关闭本issue，后续版本将会捕获该错误以避免崩溃。
